plugins {
    id 'java'
}

repositories {
    mavenCentral()
    mavenLocal()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

ext{
    samzaVersion = '1.8.0'

}

dependencies {
    implementation("org.apache.samza:samza-api:${samzaVersion}")
    implementation("org.apache.samza:samza-kv_2.12:${samzaVersion}")
    implementation("org.apache.samza:samza-kafka_2.12:${samzaVersion}")
    implementation("org.apache.samza:samza-kv-rocksdb_2.12:${samzaVersion}")
    implementation("org.apache.samza:samza-log4j_2.12:${samzaVersion}")
    implementation("org.apache.samza:samza-kv-couchbase_2.12:${samzaVersion}")
}